TPELT = float(input("Enter TP ELT NOTE : "))
TPELN = float(input("Enter TP ELN NOTE : "))
TPVOM = float(input("Enter TP VOM NOTE :"))
DEC1 = float(input('Enter DEC1 NOTE : '))
DEC2 = float(input('Enter DEC2 NOTE : '))
ANGLAIS = float(input('Enter ANGLAIS NOTE : '))
INFO = float(input('Enter INFO NOTE : '))
PROBA = float(input('Enter PROBA NOTE : '))
ELN = float(input('Enter ELN NOTE : '))
ELT = float(input('Enter ELT NOTE : '))
VOM = float(input('Enter VOM NOTE : '))
MATH = float(input('Enter MATH NOTE : '))
moy = ((TPELT*0.5)+(TPELN*0.5)+(TPVOM)+(DEC1)+(DEC2)+(ANGLAIS)+(INFO)+(PROBA*2)+(ELN*2)+(ELT*2)+(VOM*2)+(MATH*3))/17
print(f"your moyenne is {moy}")
